-- ═══════════════════════════════════════════════════
-- Admin roles, activity log, and global undo/redo
-- ═══════════════════════════════════════════════════

-- ───────────────────────────────────────────────────
-- Profiles: add admin flag
-- ───────────────────────────────────────────────────
alter table profiles
  add column if not exists is_admin boolean not null default false;

-- Helper function for admin checks in RLS policies
create or replace function is_admin(user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from profiles p
    where p.id = user_id
      and p.is_admin = true
  );
$$;

grant execute on function is_admin(uuid) to authenticated;

-- ───────────────────────────────────────────────────
-- Collaborative permissions for global undo/redo
-- ───────────────────────────────────────────────────
drop policy if exists "Creator can update custom_systems" on custom_systems;
drop policy if exists "Creator can delete custom_systems" on custom_systems;
create policy "Any authenticated user can update custom_systems"
  on custom_systems for update to authenticated using (true);
create policy "Any authenticated user can delete custom_systems"
  on custom_systems for delete to authenticated using (true);

drop policy if exists "Creator can update custom_planets" on custom_planets;
drop policy if exists "Creator can delete custom_planets" on custom_planets;
create policy "Any authenticated user can update custom_planets"
  on custom_planets for update to authenticated using (true);
create policy "Any authenticated user can delete custom_planets"
  on custom_planets for delete to authenticated using (true);

drop policy if exists "Creator can update custom_fleets" on custom_fleets;
drop policy if exists "Creator can delete custom_fleets" on custom_fleets;
create policy "Any authenticated user can update custom_fleets"
  on custom_fleets for update to authenticated using (true);
create policy "Any authenticated user can delete custom_fleets"
  on custom_fleets for delete to authenticated using (true);

-- ───────────────────────────────────────────────────
-- Activity Log (admin-only read)
-- ───────────────────────────────────────────────────
create table if not exists activity_logs (
  id          bigint generated by default as identity primary key,
  event_type  text not null,
  entity_type text,
  entity_id   text,
  message     text not null,
  metadata    jsonb,
  actor_id    uuid not null references profiles(id) on delete cascade,
  created_at  timestamptz not null default now()
);

alter table activity_logs enable row level security;

create policy "Admins can read activity_logs"
  on activity_logs for select to authenticated
  using (is_admin(auth.uid()));

create policy "Authenticated users can insert activity_logs"
  on activity_logs for insert to authenticated
  with check (auth.uid() = actor_id);

create index if not exists idx_activity_logs_created_at
  on activity_logs(created_at desc);

-- ───────────────────────────────────────────────────
-- Action History (global undo/redo)
-- ───────────────────────────────────────────────────
create table if not exists action_history (
  id          bigint generated by default as identity primary key,
  action_type text not null,
  do_payload  jsonb not null,
  undo_payload jsonb not null,
  actor_id    uuid not null references profiles(id) on delete cascade,
  undone_at   timestamptz,
  undone_by   uuid references profiles(id) on delete set null,
  discarded   boolean not null default false,
  created_at  timestamptz not null default now()
);

alter table action_history enable row level security;

create policy "Admins can read action_history"
  on action_history for select to authenticated
  using (is_admin(auth.uid()));

create policy "Authenticated users can insert action_history"
  on action_history for insert to authenticated
  with check (auth.uid() = actor_id);

create policy "Admins can update action_history"
  on action_history for update to authenticated
  using (is_admin(auth.uid()))
  with check (is_admin(auth.uid()));

create index if not exists idx_action_history_active
  on action_history(discarded, undone_at, id desc);

-- Any new action clears previously undone actions (redo branch)
create or replace function clear_redo_branch_on_action_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update action_history
  set discarded = true
  where discarded = false
    and undone_at is not null;

  return new;
end;
$$;

drop trigger if exists trg_clear_redo_branch_on_action_insert on action_history;
create trigger trg_clear_redo_branch_on_action_insert
before insert on action_history
for each row execute function clear_redo_branch_on_action_insert();

-- ───────────────────────────────────────────────────
-- Realtime publication
-- ───────────────────────────────────────────────────
do $$
begin
  begin
    alter publication supabase_realtime add table activity_logs;
  exception
    when duplicate_object then null;
  end;

  begin
    alter publication supabase_realtime add table action_history;
  exception
    when duplicate_object then null;
  end;
end $$;
